spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev  #开发环境
  application:
    name: microservicecloud-config-houliu-dev
---
spring:
  profiles: test  #测试环境
  application:
    name: microservicecloud-config-houliu-test
# 保存为 U8 格式